name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: run test
        run: sh test.sh

      - name: archive generated files
        uses: actions/upload-artifact@v4
        with:
          name: generated-file-${{ matrix.os }}
          path: examples/laravel10-app/resources/js/types
